### ISSUE TITLE
j/k navigation doesn't work for longer notes

### ISSUE THREAD

**Issue by Craftidore** [kometenstaub/obsidian-vim-reading-view-navigation#10]
J/K navigation often doesn't work right in longer notes.

- Long note with many callouts (378 lines): 
    - When at the top of the note, j/k don't work at all. 
    - When the mouse is used to scroll partially down the note, k scrolls up slightly and j scrolls up by larger amounts; neither scrolls down.
- Long note without any callouts (270 lines):
    - When at the top, j will scroll down slightly with each keypress (less than a line), but stops being able to scroll 6-ish lines down for me. k works fine.

Obsidian version (and installer version): 0.15.9

I have plenty of other plugins installed and enabled, but since you said you think you knew what the issue was, I haven't gone to test this without any plugins enabled.

**Comment by kometenstaub** [comment]
For the top of the document, that’s an issue if you hide the metadata from my experience. 

Generally, increasing the scroll amount helps. 

I thought you meant the G issue that it takes a long time, but the best thing is probably to look into the obsidian source to see what it does for the arrow, end and home keys, unless that is built into chromium.

**Comment by kometenstaub** [comment]
I set the default scroll difference to 4, that may help a little already.

**Comment by kometenstaub** [comment]
@Craftidore Do you have a repro note for me? Feel free to DM it to me on Discord if you don't want to share it publicly because I cannot reproduce this in 50-150KB files.

**Comment by Craftidore** [comment]
DMed to you.

**Comment by Craftidore** [comment]
This has been resolved with one of the recent updates ([BRAT](https://github.com/TfTHacker/obsidian42-brat) wasn't updating it correctly for some reason)
