### ISSUE TITLE
`j` does not work when scrolled to the top and the note has YAML

### ISSUE THREAD

**Issue by zhaoshenzhai** [kometenstaub/obsidian-vim-reading-view-navigation#3]
Steps to reproduce:
1. In preview mode, scroll to the top.
2. Switch to edit mode, and add a valid YAML frontmatter.
3. Switch back to preview mode.
4. Press `j`.
5. Notice that it does **not** scroll down.

Observations:
- Everything works as long as the note either:
    - Does **not** have a YAML
    - Has a YAML, but scrolled down a bit
- The `getScroll` method returns NaN if scrolled to the top. I fixed it to return `0` in that case, but the issue persists.
- Noticed this issue while working on #2, but the issue persists with a fresh vault and a fresh install of the plugin (that is, without my changes).

**Comment by zhaoshenzhai** [comment]
I will test some more and try to figure out what's wrong after #2.

**Comment by kometenstaub** [comment]
Huh, that works for me.

**Comment by kometenstaub** [comment]
The issue might be that I don't hide the YAML block. Some themes offer to have it unhide on hovering a small button, and then it needs `j` multiple times to go down.

By default, it is also hidden.

**Comment by zhaoshenzhai** [comment]
This seems to be the issue, thanks!
